////script for AREA God Simplex
//
//#1200
//Anti quit.~
//2 c 100
//quit~
//wsend %actor% Powerful forces keep you here. 
//~
//#1201
//No recall~
//2 c 100
//recall~
//*This trigger prevents people from recalling.
//wsend %actor% Divine forces prevent you from doing that.
//~
//#1202
//Justice sword~
//1 j 100
//~
//* test trigger
//%echo% actor : %actor%
//wait 10
//if (%actor.level% < 34)
//   osend %actor% The sword whispers: I will not serve you!
//   wait 2
//   %echoaround% %actor% The sword exclaims: 'I will not serve those without honour.'
//   odamage %actor% 100
//   opurge self
//else
//   osend %actor% The sword whispers: I was made to serve, great one!
//   wait 2
//   %echoaround% %actor% The sword exclaims: 'I will serve you honourable one..'
//end
//~
//#1203
//Health-Gain~
//2 c 100
//chant~
//if ("%arg%" == "incantation")
//%send% %actor% Your eyes glow white and you start to chant some incantations.
//%damage% %actor% -500
//end
//~
//#1204
//Portal-Main Chamber~
//1 c 100
//enter~
//if ("%arg%" == "portal")
//wait 1
//%send% %actor% A whirl of white light falls into your eyes, you fall into a huge water fall.
//%echoaround% %actor.name% A whirl of white light falls into %actor.name% eyes, and %actor.heshe% falls into a huge water fall that appears under %actor.hisher% feet. 
//wteleport %actor% 3001
//wait 1
//%force% %actor% look
//end
//~
//#1208
//Welcor test trigger~
//2 d 100
//*~
//%echo% self.var  is %self.var%.
//%echo% actor.eq(hold) is %actor.eq(hold)%
//%echo% testvar is %testvar%
//eval testvar %actor.eq(hold)%
//%echo% testvar is %testvar%
//%echo% testvar.id is %testvar.id% (%testvar.name%)
//%echo% test is %.id% (%.name%)
//%echo% sends the text $$2 to the room.
//~
//#1212
//Constant Raining~
//2 b 1
//~
//if ("%WeatherManivo%" == "bad")
//wecho The rain calms down to a subtle shower.
//set WeatherManivo good
//else
//wecho The rain turns stronger and starts pouring bucketfulls at a time.
//set WeatherManivo bad
//end
//~
//#1213
//new trigger~
//2 h 100
//~
//set testvar This is a Test!! :)
//%echo% %testvar%
//remote testvar %actor.id%
//~
//#1217
//new trigger~
//1 c 1
//use~
//eval objectname %arg.car%
//if %objectname% != feather
//  return 0
//  halt
//end
// 
//eval targetname %arg.cdr%
//if !(%targetname%)
//  return 0
//  halt
//end
// 
//switch %self.vnum%
//  case 12502
//    set new_vnum 12520
//    set fire 1
//    break
//  case 12520
//    set new_vnum 12521
//    set fire 1
//    break
//  case 12521
//    set new_vnum 12522
//    set fire 1
//    break
//  case 12522
//    set new_vnum 12522
//    set fire 0
//    break
//done
// 
//otransform %new_vnum%
// 
//if %fire%
//  dg_cast 'portal' %targetname%
//  %echo% A portal springs to life in front of you.
//else
//  %send% %actor% The feather seems powerless.
//end
//~
//#1220
//book keeping~
//2 c 100
//heh~
//if (%actor.name% == Rhunter)
//wait 1
//%echoaround% Jennie smiles and says, 'Hello hubby, how is it going?'
//wait 1
//%echoaround% Jennie kisses %actor% lovingly.
//end
//~
//#1233
//Rumble's Test Trigger~
//2 q 100
//~
//      if (%direction% == east)
//   %send% %actor% The door slides open, you enter, and it quickly slides shut behind you.
//   wait 1
//   %echoaround% %actor.name% The door slides open, %actor.name% walks in, and the door slides shut.
//   wait 1
//   elseif (%direction% == west)
//   wait 1
//%send% %actor% The door slides open, you leave, and it quickly slides shut behind you.
//   %echoaround% %actor.name% The door slides open, %actor.name% walks out, and the door slides shut.
//~
//#1267
//secret drawer magic~
//1 c 4
//look~
//if (%arg% == drawer)
//%purge% drawer
//%load% obj 7711
//%echo% The small drawer appears to be nothing more than a mere crack underneath the
//%echo% desk.  The only thing that gives it away is the small keyhole that winks at you
//%echo% upon closer inspection.    
//return 1
//else
//return 0
//end
//~
//#1268
//autolook for (rm 1269) Elaseth's Oubliette~
//2 g 100
//~
//%echo%  @n
//%echo%  @n
//%echo% @DWelcome to hell. Next time heed the gods, they don't play games.@n
//~
//#1269
//harp~
//0 d 100
//play~
//%echo% Hello Mister Sam.  Tu joues comme un fou!
//~
//#1270
//switch~
//1 j 100
//~
//wait 5
//if (%actor.name% != windwillow)
//osend %actor% The switch says, 'Geez.'
//opurge self
//%damage% %actor% 2020
//else
//osend %actor% The switch says, 'Fine... fine.'
//end
//~
//#1290
//actor.eq(*) test~
//0 g 100
//~
//if !%actor.eq(*)%
//  Say you are wearing nothing!
//else
//  say you are wearing something.
//end
//~
//#1291
//test trigger (booleans)~
//0 j 100
//~
//eval result (1<2)
//%echo% (1<2)       : %result%
//eval result (1 < 2)
//%echo% (1 < 2)     : %result%
//eval result (one<two)
//%echo% (one<two)   : %result%
//eval result (1 != 1)
//%echo% (1 != 1)    : %result%
//eval result (1!=1)
//%echo% (1!=1)      : %result%
//~
//#1292
//crash test find done~
//2 g 100
//~
//%echo% My trigger commandlist is not complete!
//while %people%
//  %echo% while fired without a done.
//while
//~
//#1293
//crash test dummy~
//0 b 100
//~
//eval pause2 %random.25
//%echo% pause2 %pause2%
//~
//#1294
//test trigger~
//2 abg 100
//~
//wait until 2:00
//%echo% firing
//*if %self.people%
//  eval testtarget %self.people%
//  while (%testtarget%)
//    set tmp_target %testtarget.next_in_room%
//    if %testtarget.vnum% == -1
//      %echo% player
//    end
//    set testtarget %tmp_target%
//  done
//*end
//~
//#1295
//test trigger~
//0 d 100
//test~
//%echo% Trigger fired.
//eval room %self.room%
//say room.north: %room.north%
//~
//#1296
//Random eq example~
//0 n 100
//~
//switch %random.5%
//  case 1
//    %load% obj 3010
//    wield dagger
//    break
//  case 2
//    %load% obj 3011
//    wield sword
//    break
//  case 3
//    %load% obj 3012
//    wield club
//    break
//  case 4
//    %load% obj 3013
//    wield mace
//    break
//  case 5
//    %load% obj 3014
//    wield sword
//    break
//  default
//    * this should be here, even if it's never reached
//    break
//done
//~
//#1297
//find end test~
//1 c 1
//*~
//switch %cmd%
//  case StartMusic
//    if (%musicplaying%==1)
//      %send% %actor% You are already playing music!
//      halt
//    else
//      eval musicplaying 1
//      global musicplaying
//      osend %actor% You start playing guitar.
//      oechoaround %actor% %actor.name% starts playing guitar.
//      wait 2s
//      eval flourish 3
//      global flourish
//      while (%musicplaying% == 1)
//        switch %flourish%
//          case 1
//            eval flourish a wicked guitar solo.
//            break
//          case 2
//            eval flourish a chorus riff.
//            break
//          default
//            eval flourish a steady rhythm.
//            break
//        done
//        %echoaround% %actor% %actor.name% performs %flourish%
//        %send% %actor% You perform %flourish%
//        eval flourish %random.5%
//        global flourish
//        wait 10s
//      done
//      halt
//    break
//  case StopMusic
//    if (%musicplaying%==0)
//      %send% %actor% You are not currently playing music.
//      halt
//    else
//      unset musicplaying
//      unset flourish
//      %send% %actor% You stop playing music.
//      %echoaround% %actor% %actor.name% stops playing music.
//      %force% %actor% bow
//      halt
//  case PlaySolo
//    eval flourish 1
//    global flourish
//    break
//  case PlayChorus
//    eval flourish 2
//    global flourish
//    break
//  case PlayVerse
//    eval flourish 3
//    global flourish
//    break
//  default
//    return 0
//    break
//done
//~
//#1298
//Quest object loader~
//0 j 100
//~
//context %actor.id%
//say object vnum: %object.vnum%
// 
//set answer_yes say Yes, I want that object :)
//set answer_no say I already have that object !
//set answer_reward say There you go. Here's an object for you. Thanks!
// 
//if (%object.vnum% == 1301)
//  if (%zone_12_object1%)
//    %answer_no%
//    return 0
//  else
//    %answer_yes%
//    set zone_12_object1 1
//    global zone_12_object1
//  end
//elseif (%object.vnum% == 1302)
//  if (%zone_12_object2%)
//    %answer_no%
//    return 0
//  else
//    %answer_yes%
//    set zone_12_object2 1
//    global zone_12_object2
//  end
//elseif (%object.vnum% == 1303)
//  if (%zone_12_object3%)
//    %answer_no%
//    return 0
//  else
//    %answer_yes%
//    set zone_12_object3 1
//    global zone_12_object3
//  end
//elseif (%object.vnum% == 1304)
//  if (%zone_12_object4%)
//    %answer_no%
//    return 0
//  else
//    %answer_yes%
//    set zone_12_object4 1
//    global zone_12_object4
//  end
//else
//  say I do not want that object!
//  return 0
//end
// 
//if (%zone_12_object1% && %zone_12_object2% && %zone_12_object3% && %zone_12_object4%) 
//  %answer_reward%
//  eval zone_12_reward_number %actor.zone_12_reward_number%+1
// 
//  * cap this to a max of 12 rewards.
//  if %zone_12_reward_number%>12
//    set zone_12_reward_number 12
//  end
//  remote zone_12_reward_number %actor.id%
// 
//  *  make sure all objects from 3016 and upwards have 'reward' as an alias
//  eval loadnum 3015+%zone_12_reward_number%
//  %load% o %loadnum%
//  give reward %actor.name%
//  unset zone_12_object1
//  unset zone_12_object2
//  unset zone_12_object3
//  unset zone_12_object4
//end
//test
//~
//#1299
//test trigger~
//1 q 100
//~
//%damage% %actor% 10
//%damage% %actor% -20
//%echo% trigger fired!
//~
