#ifndef __DBDATA_H__
#define __DBDATA_H__

#include "cxx/parser_skel.hh"
#include "data_parser.hh"
#include "error.hh"

// Kind of parsed data
#define DATA_HEADER (A)

#define DATA_BAN (B)
#define DATA_BREW (C)
#define DATA_MOB (D)
#define DATA_OBJ (E)
#define DATA_COMMAND (F)
#define DATA_PREREQ (G)
#define DATA_DISABLED (H)
#define DATA_ROOM (I)
#define DATA_AREA (J)
#define DATA_CONFIG (K)
#define DATA_SPHERE (L)
#define DATA_ABILITY (M)
#define DATA_FACTION (N)
#define DATA_GOD (O)
#define DATA_PC_CLASSES (P)
#define DATA_PC_RACE (Q)
#define DATA_CLAN (R)
#define DATA_LIQUID (S)
#define DATA_MATERIAL (T)
#define DATA_UNIQUE (U)
#define DATA_HOMETOWN (V)
#define DATA_TIME (W)
#define DATA_RACE (X)
#define DATA_GROUP (Y)
#define DATA_SCHOOL (Z)
#define DATA_SUPER_RACE (aa)
// 4 free: bb -> ee

//// Tag Constants
#define TAG_Ban     (0)
#define TAG_Level     (1)
#define TAG_Flags     (2)
#define TAG_BrewFormula     (3)
#define TAG_Component     (4)
#define TAG_Cost     (5)
#define TAG_Effects     (6)
#define TAG_Command     (7)
#define TAG_Position     (8)
#define TAG_Log     (9)
#define TAG_Show     (10)
#define TAG_Disable     (11)
#define TAG_Player     (12)
#define TAG_Faction     (13)
#define TAG_Friendliness     (14)
#define TAG_God     (15)
#define TAG_Title     (16)
#define TAG_Story     (17)
#define TAG_Minor     (18)
#define TAG_Major     (19)
#define TAG_Priest     (20)
#define TAG_Alignment     (21)
#define TAG_Races     (22)
#define TAG_Classes     (23)
#define TAG_Liquid     (24)
#define TAG_Color     (25)
#define TAG_Drunk     (26)
#define TAG_Full     (27)
#define TAG_Thirst     (28)
#define TAG_Food     (29)
#define TAG_Ssize     (30)
#define TAG_Material     (31)
#define TAG_Immunities     (32)
#define TAG_Resistances     (33)
#define TAG_Vulnerabilities     (34)
#define TAG_Metal     (35)
#define TAG_Unique     (36)
#define TAG_Room     (37)
#define TAG_Group     (38)
#define TAG_Contains     (39)
#define TAG_Ability     (40)
#define TAG_Type     (41)
#define TAG_Target     (42)
#define TAG_Slot     (43)
#define TAG_Beats     (44)
#define TAG_NounDamage     (45)
#define TAG_MsgOff     (46)
#define TAG_MsgObj     (47)
#define TAG_MsgRoom     (48)
#define TAG_MobUse     (49)
#define TAG_Dispel     (50)
#define TAG_MsgDispel     (51)
#define TAG_Wait     (52)
#define TAG_Craftable     (53)
#define TAG_Prereq     (54)
#define TAG_NumberCasting     (55)
#define TAG_Casting     (56)
#define TAG_List     (57)
#define TAG_Sphere     (58)
#define TAG_Clan     (59)
#define TAG_Id     (60)
#define TAG_WhoName     (61)
#define TAG_Hall     (62)
#define TAG_Recall     (63)
#define TAG_Independent     (64)
#define TAG_Member     (65)
#define TAG_Status     (66)
#define TAG_Class     (67)
#define TAG_Attributes     (68)
#define TAG_Weapon     (69)
#define TAG_Adept     (70)
#define TAG_Thac0_00     (71)
#define TAG_Thac0_32     (72)
#define TAG_HpMin     (73)
#define TAG_HpMax     (74)
#define TAG_CastingRule     (75)
#define TAG_BaseGroup     (76)
#define TAG_DefaultGroup     (77)
#define TAG_Parent     (78)
#define TAG_Choosable     (79)
#define TAG_Abilities     (80)
#define TAG_Groups     (81)
#define TAG_Pose     (82)
#define TAG_PCRace     (83)
#define TAG_Experience     (84)
#define TAG_Size     (85)
#define TAG_Attribute     (86)
#define TAG_Language     (87)
#define TAG_Race     (88)
#define TAG_Act     (89)
#define TAG_Affect     (90)
#define TAG_Affect2     (91)
#define TAG_Offensive     (92)
#define TAG_Forms     (93)
#define TAG_Parts     (94)
#define TAG_Petition  (95)
#define TAG_ScriptAbility (257)
#define TAG_MaxCasting (258)
//// For pFile
#define TAG_Pet (97)
#define TAG_AfBy (98)
#define TAG_AfBy2 (99)
#define TAG_Address (100)
#define TAG_Alias (101)
#define TAG_ACs (102)
#define TAG_Attr (104)
#define TAG_Bin (105)
#define TAG_Bout (106)
#define TAG_Beacons (107)
#define TAG_Boards (108)
#define TAG_ClanStatus (109)
#define TAG_Condition (110)
#define TAG_Comm (111)
#define TAG_Damroll (112)
#define TAG_Dnumber (113)
#define TAG_Dtype (114)
#define TAG_DamType (115)
#define TAG_Desc (116)
#define TAG_DisabledCmd (117)
#define TAG_ExField (118)
#define TAG_Etho (120)
#define TAG_Gold (121)
#define TAG_Gset (122)
#define TAG_Hitroll (123)
#define TAG_Hometown (124)
#define TAG_HMVP (125)
#define TAG_Invis (126)
#define TAG_Inco (127)
#define TAG_Immtitle (128)
#define TAG_LastLevel (129)
#define TAG_LogO (130)
#define TAG_LnD (131)
#define TAG_LineMode (132)
#define TAG_NameAccepted (133)
#define TAG_Password (134)
#define TAG_Played (136)
#define TAG_Pnts (137)
#define TAG_Prac (138)
#define TAG_Prompt (139)
//#define TAG_QuestNext (140)
//#define TAG_QuestCount (141)
//#define TAG_QuestObj (142)
//#define TAG_QuestObjLoc (143)
//#define TAG_QuestMob (144)
//#define TAG_QuestGiver (145)
#define TAG_SavingThrow (146)
#define TAG_Scroll (147)
#define TAG_Sex (148)
#define TAG_ShD (149)
#define TAG_Security (150)
#define TAG_Silver (151)
#define TAG_Stance (152)
#define TAG_Train (153)
#define TAG_Trust (154)
#define TAG_Trivia (155)
#define TAG_Version (156)
#define TAG_Wimpy (157)
#define TAG_Wiznet (158)
#define TAG_Enchanted (159)
#define TAG_ExtraFlags (160)
#define TAG_ExtraDescr (161)
#define TAG_ItemType (162)
#define TAG_Owner (163)
#define TAG_Oldstyle (164)
#define TAG_Restriction (165)
#define TAG_Spell (166)
#define TAG_Timer (167)
#define TAG_Values (168)
#define TAG_WearFlags (169)
#define TAG_WearLoc (170)
#define TAG_Weight (171)
#define TAG_Obj (172)
#define TAG_Name (173)
//#define TAG_QuestPnts (174)
//// For areas
#define TAG_Mobile (175)
#define TAG_Hit (176)
#define TAG_Psp (177)
#define TAG_Damage (178)
#define TAG_Wealth (179)
#define TAG_Program (180)
#define TAG_Special (181)
#define TAG_Shop (182)
#define TAG_Upgrade (183)
#define TAG_Sector (184)
#define TAG_MaxSize (185)
#define TAG_Rate (186)
#define TAG_Guilds (187)
#define TAG_Repop (188)
#define TAG_Exit (189)
#define TAG_Reset (190)
#define TAG_Area (191)
#define TAG_Builders (192)
#define TAG_Vnums (193)
#define TAG_Credits (194)
#define TAG_Mana (195)
#define TAG_Object (196)
#define TAG_Config (197)
#define TAG_Port (198)
#define TAG_Bug (199)
#define TAG_Typo (200)
#define TAG_Hints (201)
#define TAG_Brew (202)
//// For config file
#define TAG_Clans (203)
#define TAG_HallFame (204)
#define TAG_PCRaces (205)
#define TAG_PCClasses (206)
#define TAG_Gods (207)
#define TAG_Commands (208)
#define TAG_Disabled (209)
#define TAG_Factions (210)
#define TAG_Spheres (211)
#define TAG_Prerequisites (212)
#define TAG_Skills (213)
#define TAG_Spells (214)
#define TAG_Powers (215)
#define TAG_Songs (216)
#define TAG_Script_List (217)
#define TAG_Help_List (218)
#define TAG_Area_List (219)
#define TAG_Shutdown (220)
#define TAG_Copyover (221)
#define TAG_Last_Command (222)
#define TAG_Script_Dump (223)
#define TAG_Player_Dir (224)
#define TAG_God_Dir (225)
#define TAG_Script_Dir (226)
#define TAG_Note_Dir (227)
#define TAG_Area_Dir (228)
#define TAG_Temp (229)
#define TAG_Help_Dir (230)
#define TAG_Dump_Dir (231)
#define TAG_Data_Verbose (233)
#define TAG_Script_Verbose (234)
#define TAG_Wizlock (238)
#define TAG_Newlock (239)
#define TAG_GC_Verbose (246)
#define TAG_Test_Charmies (247)
#define TAG_Capture_SIGSEGV (248)
#define TAG_GC_Use_Entire_Heap (249)
#define TAG_GC_Dont_Expand (250)
#define TAG_GC_Dont_GC (251)
#define TAG_Default_Race (252)
#define TAG_Default_God (253)
#define TAG_Default_Hometown (254)
#define TAG_Default_Size (255)
#define TAG_Default_Language (256)
#define TAG_Data_Min_Security (259)
#define TAG_Script_Min_Security (260)
#define TAG_Default_Recall (261)
#define TAG_Default_Hall (262)
#define TAG_Default_Script_Filename (263)
#define TAG_Dump_Mob_Msg (264)
#define TAG_Save_State_On_Copyover (265)
#define TAG_Start_World_State (266)
#define TAG_Forbidden_List (267)
#define TAG_Default_Group (268)
#define TAG_Max_Heap_Size (270)
#define TAG_Daze (271)
#define TAG_Stunned (272)
#define TAG_Hunting (273)
#define TAG_BettedOn (274)
#define TAG_BetAmt (275)
#define TAG_Challenged (276)
#define TAG_Remort (277)
#define TAG_Min_Num_Remort (278)
#define TAG_Remort_Count (279)
#define TAG_Monitoring_File (280)
#define TAG_Affects (281)
#define TAG_School (282)
#define TAG_School_File (283)
#define TAG_Rebirth (284)
#define TAG_Default_PC_Race (285)
#define TAG_Morgue (286)
#define TAG_Donation (287)
#define TAG_Default_Morgue (288)
#define TAG_Default_Donation (289)
#define TAG_Default_School (290)
#define TAG_Stat_Dir (300)
#define TAG_Start_With_Saved_Time (301)
#define TAG_Clazz (302)
#define TAG_Needed_Script (303)
#define TAG_Social (304)
#define TAG_Use_Faction_On_Aggro (305)
#define TAG_Html_Dir (306)
#define TAG_Aggr_Verbose (307)
#define TAG_IsWildMagic (308)
#define TAG_AcceptWildMagic (309)
#define TAG_Needed_Obj (310)
#define TAG_Needed_Mob (311)
#define TAG_Super_Race (312)
#define TAG_Super_Races (313)
//// for area state
#define TAG_AreaState (232)
#define TAG_Master (235)
#define TAG_Fighting (236)
#define TAG_Ptr (237)
#define TAG_Leader (269)
//// for time file
#define TAG_Time (240)
#define TAG_Hour (241)
#define TAG_Date (242)
#define TAG_Change (243)
#define TAG_mmHg (244)
#define TAG_Moons (245)
#define TAG_Violence (292)
#define TAG_Point (293)
#define TAG_Auction (294)
#define TAG_Hint (295)
#define TAG_ArenaStart (296)
#define TAG_Arena (297)
#define TAG_Quake (298)
#define TAG_DoubleXp (299)
#define TAG_DoubleXpDuration (291)


const char *duplicate( const char *input, const char c );
const char *quotify( const char *input, const char *quote = "'" );
const char *list_flag_string( long flag, struct flag_type *flag_table, const char *quote = "'", const char *separator = ", " );
const char *list_flag_string_init( const long flag, struct flag_type *flag_table, const char *quote = "'", const char *separator = ", " );
long list_flag_value( DATAExpression *flag, struct flag_type *flag_table );
long list_flag_value_complete( DATAExpression *flag, struct flag_type *flag_table );
long list_flag_value( ValueList *list, struct flag_type *flag_table );
long list_flag_value_complete( ValueList *list, struct flag_type *flag_table );
const char * create_classes_list( const int count, int *classes );
const char * create_races_list( const int count, int *races );
const char * create_abilities_list( const int count, int *abilities );
const char * create_alignment_list( const int count, ALIGN_INFO *align );
const char * create_groups_list( const int count, int *groups );


//#define CASE_TAG( tagToTest ) if ( ( tagMatched == FALSE ) && tagId == (tagToTest) && (tagMatched = TRUE) )
//void assign_tags();

int find_tag( const char *tagName, int whichData = -1 );
int parse_datas( FILE *fp );
// 2 following methods represents parse_datas but split in 2 parts
//  in case we want to do something special with the module
// or read many modules before extracting informations from them, ...
DATAModule *get_data_module( FILE *fp );
int parse_data_module( DATAModule *module );


void check_tags();

// used only in config.C
void addContext( const char *varName, DATAExpression *varValue );
// used only in data_execute.cc
Value* getContext( const char *varName );


extern int data_depth;
void sh_fprintf( FILE *fp, const char *str, ... );
bool old_parse_affect( DATAData *pafD, AFFECT_DATA *paf );
void old_save_affects( AFFECT_DATA *paf, FILE *fp );
bool parse_affect( DATAData *pafD, AFFECT_DATA *paf );
void new_save_affect( AFFECT_DATA *paf, FILE *fp );

#endif
